name: cafe_letter
description: "오늘의 나, 미래의 너에게. 적적한 카페에서 써 내려가는 나만의 타임캡슐"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'




dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_mobile_ads: ^4.0.0
  flutter_local_notifications: ^16.3.2


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NanumPen
      fonts:
        - asset: assets/fonts/NanumPenScript-Regular.ttf
